### ISSUE TITLE
Timeout with large files

### ISSUE THREAD

**Issue by MikeUnwalla** [danielnaber/oxygen-languagetool-plugin#9]
A test file contains approximately 4000 lines, each line of which is 'This is a example input to to show you how LanguageTool works.'

LT gives a 'timed out' message:
![oxygen-time-out](https://cloud.githubusercontent.com/assets/5816160/20836532/ae8db166-b897-11e6-83c2-f5514fa84b1c.png)

The number of lines at which the error occurred was not constant. But with approximately 3000 lines I did not get the 'timed out' message.

**Comment by danielnaber** [comment]
How long was the time between starting the check and getting the timeout message?

**Comment by MikeUnwalla** [comment]
Approximately 42 seconds.

-----Original Message-----

**Comment by danielnaber** [comment]
I can reproduce this. Full stack trace:

	391401 INFO [ Thread-10 ] org.apache.http.impl.execchain.RetryExec - Retrying request to {}->http://localhost:8081
	java.lang.RuntimeException: Could not check text using LanguageTool server at URL 'http://localhost:8081':

	ro.sync.net.protocol.http.abstraction.f: Read timed out (http://localhost:8081/v2/check)

	Please make sure the LanguageTool server is running at this URL or
	change the location at Options -> Preferences... -> Plugins.
		at org.languagetool.oxygen.LanguageToolClient.checkText(LanguageToolClient.java:73)
		at org.languagetool.oxygen.LanguageToolPluginExtension.checkText(LanguageToolPluginExtension.java:213)
		at org.languagetool.oxygen.LanguageToolPluginExtension.access$400(LanguageToolPluginExtension.java:58)
		at org.languagetool.oxygen.LanguageToolPluginExtension$5.run(LanguageToolPluginExtension.java:163)
		at java.lang.Thread.run(Thread.java:745)
	Caused by: java.lang.RuntimeException: ro.sync.net.protocol.http.abstraction.f: Read timed out (http://localhost:8081/v2/check)
		at org.languagetool.remote.RemoteLanguageTool.getConnection(RemoteLanguageTool.java:154)
		at org.languagetool.remote.RemoteLanguageTool.check(RemoteLanguageTool.java:119)
		at org.languagetool.remote.RemoteLanguageTool.check(RemoteLanguageTool.java:62)
		at org.languagetool.oxygen.LanguageToolClient.checkText(LanguageToolClient.java:56)
		... 4 more
	Caused by: ro.sync.net.protocol.http.abstraction.f: Read timed out (http://localhost:8081/v2/check)
		at ro.sync.net.protocol.http.b.d.j(Unknown Source)
		at ro.sync.net.protocol.http.abstraction.o.s(Unknown Source)
		at ro.sync.net.protocol.http.abstraction.o.f(Unknown Source)
		at ro.sync.net.protocol.http.WebdavHttpURLConnection$_c.close(Unknown Source)
		at java.io.FilterOutputStream.close(FilterOutputStream.java:159)
		at org.languagetool.remote.RemoteLanguageTool.getConnection(RemoteLanguageTool.java:151)
		... 7 more

**Comment by danielnaber** [comment]
Okay, I now know to fix this: by adding e.g. `conn.setReadTimeout(5*60*1000);` to `RemoteLanguageTool.getConnection()`. Is this an urgent issue for you? I'm not so sure it makes sense to increase the timeout to several minutes, as long as there's no visual feedback for the user about the progress of the check.

**Comment by MikeUnwalla** [comment]
It's not an urgent problem. (I have not received complaints from customers!)

I agree that increasing the timeout when there is no indication of progress is not sensible. A note about the timeout in the 'Known Limitations' section of the download page would be useful.

**Comment by danielnaber** [comment]
I've added this to the "Known limitations".
